<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFG6TeCI\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFG6TeCI/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerFG6TeCI.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerFG6TeCI\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerFG6TeCI\appAppKernelProdContainer([
    'container.build_hash' => 'FG6TeCI',
    'container.build_id' => 'cb1b0e48',
    'container.build_time' => 1720707846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFG6TeCI');
