<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTHIlLyE\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTHIlLyE/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerTHIlLyE.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerTHIlLyE\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerTHIlLyE\appAppKernelProdContainer([
    'container.build_hash' => 'THIlLyE',
    'container.build_id' => '1407cb77',
    'container.build_time' => 1720707905,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTHIlLyE');
